---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubernetes-chaos.name" . }}-chaos-user
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubernetes-chaos.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubernetes-chaos.name" . }}-chaos-user
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}-chaos-sa
  namespace: {{ .Release.Namespace }}
