---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}-chaos-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubernetes-chaos.labels" . | indent 4 }}
